SAVEFILE = "Austin_Police_Stations.csv"
DOWNLOAD_URL = "https://data.austintexas.gov/api/views/jmp6-p8e2/rows.csv?accessType=DOWNLOAD"

task :default => [SAVEFILE]
  
file SAVEFILE do |t|
  sh("wget", "-O", t.name, DOWNLOAD_URL)
end
  
task :clean do
  # empty
end
  
task :clobber => [:clean] do
  rm(SAVEFILE)
end
